name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg GEMINI_APIKEY=${{ secrets.GEMINI_APIKEY }} -t ${{ secrets.DOCKER_USERNAME }}/sheet-happens:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/sheet-happens:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/sheet-happens:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sheet-happens:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sheet-happens:latest
